import localFont from "next/font/local";
import "./globals.css";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Under Construction Alert */}
        <div style={{ backgroundColor: 'yellow', color: 'black', textAlign: 'center', padding: '10px', fontSize: '16px' , position: 'fixed', zIndex: '100', width: '100%'}}>
          🚧 This website is currently under construction. 🚧
        </div>

        {children}
      </body>
    </html>
  );
}

